spring:
  application:
    name: parking-management
  
  datasource:
    url: jdbc:mysql://localhost:3306/parking_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  jackson:
    time-zone: America/Sao_Paulo
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

server:
  port: 3003

logging:
  level:
    com.estapar: DEBUG
    org.springframework.web: DEBUG

# Garage simulator configuration
garage:
  simulator:
    base-url: http://host.docker.internal:8080
    garage-endpoint: /garage

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
